openapi: 3.0.3
info:
  title: SustainaCore API
  version: 1.0.0
  description: Design-only API surface for Projects, Maintenance, Contractors, Documents, Finance, Notifications.
servers:
  - url: https://localhost:5001/api/v1
paths:
  /projects:
    post:
      summary: Create a new project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
      responses:
        '201':
          description: Created
  /tickets:
    post:
      summary: Raise a maintenance ticket
      responses:
        '201':
          description: Created
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        type: { type: string }
        title: { type: string }
        status: { type: integer }
        detail: { type: string }
        instance: { type: string }
    CreateProjectRequest:
      type: object
      required: [name, budget]
      properties:
        name: { type: string }
        budget: { type: number, format: double }
